config/routes.rb
Rails.application.routes.draw do
  root to: 'application#root'
  resources :restaurants, only: [:index, :show, :create, :update, :destroy] do
    get :options, on: :collection
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
# Restaurant model
class Restaurant < ApplicationRecord
  include ActiveModel::AttributeMethods
  include ActiveModel::Serialization

  enum genre: [:sushi, :burgers]

  attr_reader :genre_letter

  has_many :reviews, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2 }, uniqueness: true
  validates :genre, presence: true, inclusion: { in: genres.keys }
  validates :accepts_10bis, inclusion: { in: [true, false] }
  validates :rating,
            presence: true,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: 0,
              less_than_or_equal_to: 3,
            }
  validates :delivery_time,
            presence: true,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: 0,
              less_than_or_equal_to: 120,
            }

  def attributes
    {
      id: nil,
      name: nil,
      rating: nil,
      genre: nil,
      delivery_time: nil,
      accepts_10bis: nil,
      genre_letter: genre_letter,
    }
  end

  def genre_letter
    case genre.to_sym
      when :sushi
        'D'
      when :burgers
        'A'
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :name, presence: true, length: { minimum: 2 }
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 3 }

  after_save :calc_restaurant_rating!
  after_destroy :calc_restaurant_rating!

  private

  def calc_restaurant_rating!
    rating = restaurant.reviews.average(:rating) || 0
    restaurant.update!(rating: rating.round)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def create
    restaurant = Restaurant.new(restaurant_params)
    unless restaurant.save
      respond_to do |format|
        format.json { render json: restaurant.errors.messages, status: :conflict }
      end
    end
  end

  def options
    respond_to do |format|
      opts = {
        genre: Restaurant.genres.keys.to_a,
        delivery_time_min: 0,
        delivery_time_max: 120,
        ratings: [0, 1, 2, 3],
      }
      format.json { render json: opts }
    end
  end

  def index
    respond_to do |format|
      restaurants = Restaurant.all
      if filter_params[:genre]
        restaurants = restaurants.where(genre: filter_params[:genre])
      end
      if filter_params[:rating]
        restaurants = restaurants.where('rating >= ?', filter_params[:rating])
      end
      if filter_params[:delivery_time]
        restaurants = restaurants.where('delivery_time <= ?', filter_params[:delivery_time])
      end
      format.json { render json: restaurants }
    end
  end

  def show
    respond_to do |format|
      @restaurant = Restaurant.find(params[:id])
      format.json { render json: @restaurant }
      format.html { render 'show' }
    end
  end

  def destroy
    respond_to do |format|
      @restaurant = Restaurant.find(params[:id])
      @restaurant.destroy
      format.json { render json: @restaurant }
      format.html { redirect_to '/' }
    end
  end

  def update
    respond_to do |format|
      restaurant = Restaurant.find(params[:id])
      restaurant.update!(restaurant_params)
      format.json { render json: restaurant }
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :rating, :genre,
                                       :accepts_10bis, :delivery_time)
  end

  def filter_params
    params.permit(:genre, :rating, :delivery_time)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def show
    @restaurant = Restaurant.find(params[:restaurant_id])
    redirect_to restaurant_url(@restaurant)
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build(review_params)
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.create!(review_params)
    redirect_to restaurant_url(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @restaurant.reviews.find(params[:id]).destroy
    redirect_to restaurant_url(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:name, :comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/application/root.html.erb
<%= react_component('Router', prerender: false, html_options: {class: 'app-root'}) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EatNow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'webpack-bundle','data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Cambay" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/show.html.slim
div class="container"
  div class="header"
    h1 class="logo" EatNow
    | Let's find lunch now...
  div
    div class="filters row"
      a href="/"
        button class="btn btn-default" Back
  div class="content"
    div class="restaurant row"
      div class="col-xs-2 genre" #{@restaurant.genre_letter}
      div class="col-xs-8"
        p class="title" #{@restaurant.name}
        p= render partial: "reviews/rating", locals: {rating: @restaurant.rating}
        p Delivery time: up to #{@restaurant.delivery_time} minutes
      div class="col-xs-2"
        a href="/#/restaurants/#{@restaurant.id}/edit"
          button class="btn btn-default"
            span class="glyphicon glyphicon-edit"
        = form_for restaurant_path(@restaurant), html: {method: :delete} do |f| 
          = f.button class: "btn btn-default error"
            span class="glyphicon glyphicon-trash error" 
    = render @restaurant.reviews  
    = render 'reviews/form'

app/views/reviews/_form.html.slim
div class="row"
  div class="col-xs-12"
    h3 Add a review:
    = form_for([@restaurant, @restaurant.reviews.build]) do |f|
      = f.hidden_field :restaurant_id
      div class="form-group"
        = f.label :name
        = f.text_field :name, {class: "form-control"}
      div class="form-group"
        = f.label :rating
        = f.select :rating, [0,1,2,3], {}, {class: "form-control"}
      div class="form-group"
        = f.label :comment
        = f.text_area :comment, {class: "form-control"}
      div.actions
        = f.submit "Submit", {class: "btn btn-default"}

app/views/reviews/_rating.html.slim
| Rating: 
- for i in (1..rating) do
  span class="glyphicon glyphicon-star"
- for i in (rating+1..3) do
  span class="glyphicon glyphicon-star-empty"

app/views/reviews/_review.html.slim
div class="row restaurant"
  div class="col-xs-2"
    span class="title" #{review.name}
  div class="col-xs-8"
    p= render partial: "reviews/rating", locals: {rating: review.rating} 
    p #{review.comment}
  div class="col-xs-2"
    = form_for restaurant_review_path(@restaurant, review), url: restaurant_review_path(@restaurant, review), html: {method: :delete} do |f| 
      = f.button class: "btn btn-default error"
        span class="glyphicon glyphicon-trash error" 